micronaut:
  application:
    name: hello-micronaut
  server:
    port: 8899
  endpoints:
    health:
      enabled: true


mongodb:
  uri: mongodb://localhost:27017/test
  database-name: test
  collection-name: test
